project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - 404.qmd
    - resume/index.qmd
    - blog/index.qmd
    - blog/*/index.qmd
    - projects/index.qmd
    - projects/*/*/index.qmd # First star is type of project, second star is project folder
    - teaching/index.qmd
    - teaching/*/*/index.qmd # First star is type of teaching (course/workshop), second star is content folder
  resources: 
    - /**/thumbnail.jpg
    - /**/thumbnail.png
    - /**/images/*
    - /**/files/*
    - www
  preview: 
    timeout: 30
    port: 4200

# license: CC BY-NC-ND

website:
  # Info
  title: "Ozan Ozbeker"
  description: "The professional website of Ozan Ozbeker."
  site-url: https://ozanozbeker.com
  favicon: www/icons/code.svg

  # Options
  open-graph: true
  back-to-top-navigation: true
  # comments: https://quarto.org/docs/reference/projects/websites.html#giscus

  # Footer
  page-footer:
    left: "© 2025 Ozan Ozbeker | [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    right: "Website designed by me and powered by [Quarto](https://www.quarto.com)!"

  # Navbar
  navbar:
    logo: www/icons/code.svg
    search: true
    left:
      - href: resume/index.qmd
        text: Resume
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: teaching/index.qmd
        text: Teaching
  
format:
  html:
    # Layout
    page-layout: article
    number-sections: false

    # Code Options
    code-overflow: scroll
    code-copy: hover
    code-link: false
    highlight-style: nord

    # External Links
    link-external-icon: true
    link-external-newwindow: true

    # Theming
    theme: [simplex, www/theme/royal-nord-dark.scss]

    # Table of Contents
    toc: true
    toc-depth: 3

    # Other
    smooth-scroll: true

# Code Execution
execute: 
  freeze: auto
  eval: false
  cache: refresh
