project:
  type: website

  preview:
    browser: true
    watch-inputs: true
    navigate: true

  resources:
    - "**.pdf"

website:
  title: "Ozan Ozbeker"
  description: "The professional website of Ozan Ozbeker."
  llms-txt: true
  search: false
  sidebar:
    style: floating
    tools:
      - icon: github
        href: https://github.com/ozanozbeker
      - icon: linkedin
        href: https://linkedin.com/in/ozanozbeker
      - icon: envelope
        href: mailto:contact@ozanozbeker.com
    contents:
      - href: about-me/index.qmd
        text: About Me
      - href: resume/index.qmd
        text: Resume
      - href: projects/index.qmd
        text: Projects
      - href: tech-stack/index.qmd
        text: Tech Stack
      - href: teaching/index.qmd
        text: Teaching

  repo-url: https://github.com/ozanozbeker/ozanozbeker.github.io
  site-url: https://ozanozbeker.com

  page-footer:
    center: "© 2026 Ozan Ozbeker | [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"

  favicon: resources/code.svg
  twitter-card: true
  open-graph: true

format:
  html:
    grid:
      body-width: 700px
      gutter-width: 1rem

    theme:
      light:
        - simplex
        - brand
      dark:
        - simplex
        - brand

    respect-user-color-scheme: true

    toc: true
    toc-depth: 3
    toc-expand: true

    # reference-location: margin
    footnotes-hover: true

    html-math-method: katex

    smooth-scroll: true

    link-external-icon: true
    link-external-newwindow: true

brand:
  light: light-brand.yml
  dark: dark-brand.yml

execute:
  freeze: auto
