[project]
name = "ozanozbeker.com"
version = "0.1.0"
description = "My personal website."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "plotly[express]>=6.2.0",
]
