---
title: "Resume"
format:
  html: 
    number-sections: false
    toc-title: "Sections"
    other-links:
      - text: "Resume PDF"
        href: docs/ozan-ozbeker-resume.pdf
        icon: file-earmark-text
      - text: "GitHub"
        href: https://github.com/ozanozbeker/
        icon: github
      - text: "LinkedIn"
        href: https://www.linkedin.com/in/ozanozbeker/
        icon: linkedin
      - text: "Email"
        href: mailto:ozanozbeker99@outlook.com
        icon: envelope
comments: false
---

## Summary {#sec-summary}

As a **Data Scientist** at [OneMagnify](https://onemagnify.com/), I manage full-stack data science projects for Fortune 500 clients, delivering solutions that drive measurable business value. I design and implement robust ETL pipelines, create dynamic dashboards in Tableau, and develop predictive models to optimize client operations. My expertise in R, Python, SQL, and Tableau allows me to provide end-to-end support, from data engineering to business intelligence and advanced analytics, ensuring impactful and actionable insights for stakeholders.

In addition to my professional experience, I am an **Adjunct Professor** at [West Virginia University](https://www.wvu.edu/), where I redesigned and now teach *IENG 331: Computer Applications in Industrial Engineering*. By integrating industry-relevant tools like SQL, Tableau, Power BI, and advanced Excel features, I prepare students for real-world data analytics careers. My curriculum emphasizes stakeholder collaboration, project-based learning, and building analytics portfolios, empowering students with practical skills they can apply early in their careers. I also teach R for data manipulation on scale, automation, and reporting, introducing tools like Quarto to demonstrate modern, scalable data workflows.

My diverse skill set is further complemented by certifications in Lean Six Sigma and Continuous Improvement, as well as hands-on teaching experience, making me adept at leading technical and cross-functional teams to deliver data-driven results.

### Tech Stack

###### Data Manipulation & Analysis

-   **R:** [{tidyverse}](https://www.tidyverse.org/), [{duckplyr}](https://duckplyr.tidyverse.org/index.html), [{data.table}](https://rdatatable.gitlab.io/data.table/)
-   **Python:** Polars, Ibis
-   **SQL:** PostreSQL, MS SQL Server, DuckDB

###### Data Visualization & Reporting

-   **Static:** [{ggplot2}](https://ggplot2.tidyverse.org/), [{gt}](https://gt.rstudio.com/)
-   **Reactive:** [{plotly}](https://plotly.com/), [{reactable}](https://glin.github.io/reactable/index.html)

###### Dashboarding, Web Development, & Scraping

-   **Quarto:** [Static and interactive documents](https://quarto.org/)
-   **Shiny:** [Interactive dashboards and applications](https://shiny.posit.co/)
-   **Enterprise:** Tableau Desktop & Prep, MS Power BI
-   **Languages:** HTML, SASS/SCSS/CSS, Bootstrap
-   **HTTP:** [{httr2}](https://httr2.r-lib.org/)
-   **Scraping:** [{rvest}](https://rvest.tidyverse.org/), Selenium/[{RSelenium}](https://docs.ropensci.org/RSelenium/index.html)

###### DevOps & MLOps

-   **Development:** [{tidymodels}](https://www.tidymodels.org/)
-   **Deployment:** [{vetiver}](https://rstudio.github.io/vetiver-r/), [{plumber}](https://www.rplumber.io/)
-   **Containers:** Docker

## Experience {#sec-experience}

### Adjuct Professor

[[**West Virginia University**](https://www.wvu.edu/) - [**Statler College of Engineering**](https://www.statler.wvu.edu/)]{.resume-company}

[**Morgantown, WV** \| December 2024 - Current]{.resume-location-date}

As a new lecturer, I leveraged my experience as a Data Scientist at an analytics consulting firm to redesign and deliver *IENG 331: Computer Applications in Industrial Engineering*, transforming it from a traditional computer science-style course into one focused on practical data analysis skills and stakeholder collaboration. This redesign prepares students to meet the demands of modern industry roles in analytics and engineering. Key contributions and benefits include:

-   **SQL for Data Extraction:** Developed course modules providing hands-on experience with modern relational databases such as Microsoft SQL Server and PostgreSQL. Students learned the nuances of ANSI SQL versus vendor-specific syntax and capabilities, equipping them to work seamlessly with real-world data systems. This practical knowledge bridges the gap between academic concepts and industry needs, empowering students to extract and analyze data effectively in internships and early career roles.

-   **Advanced Excel for Efficiency:** Introduced advanced Excel features like Power Query and the Data Model to demonstrate efficient data transformation and analysis workflows. These tools provide students with immediate value, as Excel remains one of the most widely used platforms in industry. By mastering these capabilities, students can streamline reporting and data preparation tasks, boosting productivity in professional settings.

-   **Industry-Ready Data Visualization:** Incorporated modules on Tableau and Power BI, giving students experience with leading dashboarding tools. By integrating these platforms into class projects, students gain exposure to creating impactful, interactive visualizations that are highly sought after by employers across industries.

-   **Portfolio-Based Project Work:** Designed class assignments around real-world, project-based learning to help students build analytics portfolios. This approach enables students to showcase their practical skills during internship and job applications, giving them a competitive edge in the hiring process.

-   **Real-World Context and Stakeholder Communication:** Prepared students for careers in data analytics by simulating real-world scenarios that required effective communication with stakeholders. This included teaching industry terminology, report writing, and decision-making processes, ensuring students can bridge the technical and business aspects of analytics roles.

-   **R for Automation and Advanced Reporting:** Expanded the use of R beyond its traditional role in statistics, teaching students how to use it as a scripting language for automation, data analysis, and reporting. Introduced Quarto, a tool for creating automated, professional-grade reports that integrate R, Python, and other languages. This gives students a solid foundation in tools they can expand upon in future roles, including report automation and reproducible workflows.

### Data Scientist

[[**OneMagnify**](https://onemagnify.com/) (Previously [**Splash Analytics**](https://splashanalytics.com/))]{.resume-company}

[**Remote, USA** \| January 2023 - Current]{.resume-location-date}

As part of a boutique analytics consulting firm, I manage end-to-end data science projects across the full data stack for Fortune 500 clients in the replacement parts industry. I lead engagements from client relationship management to delivering impactful data-driven solutions.

-   **Consulting & Client Engagement:** Lead multiple high-stakes engagements with Fortune 500 clients, managing relationships, gathering requirements, and presenting tailored data solutions. My role includes conducting client meetings, setting project expectations, and delivering actionable insights, ensuring satisfaction and long-term value creation.

-   **Data Science & Analytics:** Developed weekly price recommendation models for Amazon ASINs, integrating competitive analysis, seller performance, and margin targets. Utilized NLP and sentiment analysis to assess client survey feedback, leading to internal consulting improvements. Built end-of-life part forecasts using ARIMA, ETS, Prophet, and XGBoost, optimizing inventory management for discontinued replacement parts.

-   **Business Intelligence:** Developed customized HTML reports that surpassed the limitations of traditional formats like PDF/Word/PowerPoint, offering advanced features and portability. Maintained 5 Tableau workbooks on the client's Tableau Server, delivering dashboards that provided a single view of seller performance on Amazon. These insights helped manage $30M in annual sales across 6,000 SKUs. Created competitive marketplace reports using web scraping to highlight missed revenue opportunities and counterfeit activity, helping clients strategize product offerings. 

-   **Data Engineering:** Designed and implemented robust ETL pipelines, ingesting data from FTP, Google Drive, Amazon S3, and various databases into our internal systems. Enhanced existing workflows to streamline the ingestion and transformation of large datasets across clients.

-   **DevOps & Infrastructure:** Standardized the use of Git and GitHub for version control and project management, ensuring the accuracy and integrity of SQL queries across client projects. Established database schemas and standards for client data, ensuring consistency in our project folder structures, both locally and in development environments, akin to AWS EC2 and S3.

### Operations Leadership Development Program

[[**Xylem, Inc**](https://www.xylem.com/en-us/)]{.resume-company}

[**Chicago, IL & Uniontown, PA** \| July 2021 - December 2022]{.resume-location-date}

During my two rotations as a Business Data Analyst and Continuous Improvement Engineer, I led multi-departmental teams across various sites, implementing data-driven projects and operational improvements.

-   **Excess & Obsolete Disposition Project:** Applied DMAIC/DMADV methodologies to develop a process for reducing excess and obsolete materials in warehouses, projected to generate $1M–$4M in savings over 3–5 years. Created a cross-departmental E&O task force, leveraging Process Flowcharts, Value Stream Mapping, and Control Charts to improve material rework, resale, and disposal practices.

-   **Excess & Obsolete Identification Project:** Automated the quarterly E&O reporting process by building SQL queries and Power Query-enabled Excel templates, standardizing reports across three manufacturing sites. This solution reduced the reporting process time by 90%, while meeting finance audit standards.

-   **Physical Inventory Event Overhaul:** Collaborated with Finance and Materials teams to streamline the annual cycle count event for three sites, reducing event time by one day for two sites and decreasing manager preparation time. Developed process flowcharts, work instructions, and checklists to ensure smooth execution.

-   **SQL Reporting & Automation:** Created SQL-based ad-hoc reports to validate supplier quotes, synchronize lot sizes, and measure excess inventory across work cells, improving decision-making and alignment across departments.

-   **Tableau Reporting:** Designed Tableau dashboards for internal audit teams, measuring forecasting accuracy, product quality benchmarks, and KPIs for units produced. These dashboards provided real-time insights, aiding strategic planning for Quality and Finance teams.

-   **Continuous Improvement Workshops:** Led and facilitated various workshops focused on Lean methodologies, 5S, FMEA, and Process Capability Analysis, driving continuous improvement initiatives and fostering a culture of operational excellence across multiple sites.

### Undergraduate Teaching Assistant

[[**West Virginia University**](https://www.wvu.edu/)]{.resume-company}

[**Morgantown, WV** \| August 2019 - May 2021]{.resume-location-date}

As a Teaching Assistant in the Industrial Engineering department, I supported student learning across four key courses, contributing to curriculum development and enhancing student comprehension through hands-on teaching and guidance.

-   **Spring 2021** \| IENG 220: Re-engineering Management Systems
-   **Fall 2020** \| IENG 305: Intro to Systems Engineering
-   **Spring 2020** \| IENG 331: Computer Applications in Industrial Engineering
-   **Fall 2019** \| IENG 445: Project Management for Engineers

### Manufacturing Engineer Intern

[[**JLG Industries**](https://www.jlg.com/)]{.resume-company}

[**McConnellsburg, PA** \| June 2019 - August 2019]{.resume-location-date}

During my internship at JLG Industries, I contributed to process improvements and operational efficiency on the manufacturing floor, working closely with engineering teams on key projects.

-   **Test - Inspect - Green Tag (TIG) Line:** Conducted a comprehensive 6S audit to optimize workstation layouts by eliminating unnecessary equipment and parts, which improved workflow and increased efficiency. Developed Standard Work Instructions (SWIs) from scratch for five stations, covering three different products, ensuring consistency and reliability in the inspection and tagging processes.

-   **Tire Manipulator:** Implemented a scanner-based system for defect entry into the Electronic Quality Control (EQC) system, standardizing the defect entry process and improving data accuracy. Designed detailed floor plans for both current and future station layouts using laser measurements and AutoCAD, enabling optimized workspace planning for the Tire Manipulator project.

## Education {#sec-education}

### Bachelor of Science in Industrial Engineering

[[**West Virginia University**](https://www.wvu.edu/)]{.resume-company}

[**Morgantown, WV**]{.resume-location-date}

*Industrial engineering is the discipline of engineering concerned with the design, improvement, and installation of integrated systems of people, material, information, equipment, and energy to assure performance, reliability, maintainability, schedule adherence, and cost control.*

### Certifications

-   **Lean Six Sigma Green Belt** \| Institute of Industrial and Systems Engineers
-   **Continuous Improvement Fundamentals** \| Oshkosh Corporation
-   **Eligible for Certified Associate in Project Management (CAPM)** \| Project Management Institute
